# Generated by Django 5.2.3 on 2025-06-19 10:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
